# Generated by Django 5.1.4 on 2025-01-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, help_text='Роль', max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Роль'),
        ),
    ]
