# Generated by Django 5.1.4 on 2025-01-04 19:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 4, 22, 0, 50, 895552), help_text='Дата рождения', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=1, help_text='Роль', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
